### DISCUSSION TITLE
My example of deploy by docker

### DISCUSSION THREAD

**Discussion by Bitnik212** [bongo-devs/lavamusic#651] [Show and tell]
There my docker-compose file:

```yml
version: "3.8"

services:

    # services for postgresql database
    postgres:
       image: postgres:16-alpine
       restart: on-failure
       environment:
         POSTGRES_USER: lavamusic
         POSTGRES_PASSWORD: lavamusic
         POSTGRES_DB: lavamusic
       volumes:
         - pg_data:/var/lib/postgresql/data
       healthcheck:
         test: 'pg_isready -U lavamusic'
         interval: 10s
         timeout: 10s
         retries: 5
         start_period: 10s

    # services for lavamusic
    lavamusic:
      image: ghcr.io/appujet/lavamusic:main
      environment:
        # Your lavalink url
        LAVALINK_URL: $LAVALINK_URL
        # Your lavalink password
        LAVALINK_AUTH: $LAVALINK_AUTH
        # Your lavalink name
        LAVALINK_NAME: $LAVALINK_NAME
        # Your lavalink secure (true or false)
        LAVALINK_SECURE: "true"
        PRODUCTION: "true"
        PREFIX: "/"
        GUILD_ID: "DELETED"
        DEFAULT_LANGUAGE: "EN"
        OWNER_IDS: "DELETED"
        TOKEN: $TOKEN # Your bot token.
        CLIENT_ID: $CLIENT_ID # Your bot's client ID (If this value is left blank, bots cannot be invited using /invite or /about commands.).
        BOT_STATUS: "online" # Your bot status (online, dnd, idle, invisible or offline).
        BOT_ACTIVITY_TYPE: 0 # Activity type is a number from 0 to 5. See more here: https://discord.com/developers/docs/topics/gateway-events#activity-object-activity-types
        BOT_ACTIVITY: "Lavamusic" # Your bot activity.
        AUTO_NODE: "false" # true for auto node. It is given from lavainfo-api (https://lavainfo-api.deno.dev)."localhost:2333" # Your Lavalink url (If auto node is true, then you can leave it blank).
        MAX_PLAYLIST_SIZE: "1000" # Max playlist size.
        MAX_QUEUE_SIZE: "1000" # Max queue size.    
        DATABASE_URL: "postgresql://lavamusic:lavamusic@postgres:5432/lavamusic"
      restart: on-failure
      volumes:
        - "/home/bit/lavamusic/locales:/opt/lavamusic/languages/locales"
      depends_on:

        - postgres


volumes:
  pg_data:
```
  
Replace by your data:
- GUILD_ID
- OWNER_IDS
- CLIENT_ID
- TOKEN
- LAVALINK_URL
- LAVALINK_AUTH
- LAVALINK_NAME

Note:
Don't add 443 port to LAVALINK_URL
